package main

// Windows PE resources for WorthyJoin-Host.exe (app icon for Explorer / shortcuts / taskbar).
// Regenerated by: go run ./cmd/connect-host/genicon.go && go run ./cmd/connect-host/genrsrc.go
//
//go:generate go run ./genicon.go
//go:generate go run ./genrsrc.go
